import { Hotel } from './hotel';

// Список готелів
export const HOTELS: Hotel[] = [
    // Готелі для країни з id_country = 1 (Greece)
    new Hotel(1, 'Hotel Athens', 1, 1, 'A cozy hotel located in the heart of Athens, offering breathtaking views of the Acropolis. Perfect for both leisure and business travelers.', 'Standard room', 'Only Breakfast', 'Near the Acropolis and city center', '10m to the beach', 'Acropolis Avenue 123', '+123456789', 'athens@example.com', ['Free Wi-Fi', 'Free Parking'], 'Hotel has 3 floors. The hotel consists of a three-story building. There are 23 rooms in total.', 5),
    new Hotel(2, 'Hotel Thessaloniki', 2, 1, 'Modern hotel situated in the bustling city center of Thessaloniki. Enjoy luxurious accommodations and top-notch amenities during your stay.', 'Luxury suite', 'Only Dinner', 'Close to Aristotelous Square', '20m to the beach', 'Aristotelous Street 45', '+987654321', 'thessaloniki@example.com', ['Swimming Pool', 'Gym'], 'Hotel has 5 floors. The hotel consists of a five-story building. There are 35 rooms in total.', 3),
    new Hotel(3, 'Hotel Patras', 3, 1, 'A family-friendly hotel located near the port of Patras. Experience warm hospitality and comfortable rooms with beautiful sea views.', 'Family room', 'All Inclusive', 'Conveniently located near the port', '15m to the beach', 'Othonos-Amalias Street 17', '+1122334455', 'patras@example.com', ['Spa', 'Restaurant'], 'Hotel has 2 floors. The hotel consists of a two-story building. There are 20 rooms in total.', 20),
    new Hotel(4, 'Hotel Heraklion', 4, 1, 'Charming hotel situated in the historic city of Heraklion. Relax in elegantly designed rooms and enjoy easy access to the city\'s attractions.', 'Standard room', 'Only Breakfast', 'Central location in Heraklion', '30m to the beach', 'Korai Street 88', '+9988776655', 'heraklion@example.com', ['Bar', 'Room Service'], 'Hotel has 4 floors. The hotel consists of a four-story building. There are 40 rooms in total.', 40),

    // Готелі для країни з id_country = 2 (Italy)
    new Hotel(5, 'Hotel Rome', 5, 2, 'Elegant hotel located near the iconic landmarks of Rome. Immerse yourself in the rich history and culture of the Eternal City.', 'Deluxe room', 'Only Breakfast', 'In the heart of Rome', '10m to the beach', 'Via del Corso 123', '+123456789', 'rome@example.com', ['Free Wi-Fi', 'Restaurant'], 'Hotel has 6 floors. The hotel consists of a six-story building. There are 60 rooms in total.', 60),
    new Hotel(6, 'Hotel Naples', 6, 2, 'Comfortable hotel nestled in the charming city of Naples. Experience genuine Italian hospitality and explore the city\'s vibrant neighborhoods.', 'Standard room', 'Only Dinner', 'Close to the historic center', '25m to the beach', 'Via Toledo 56', '+987654321', 'naples@example.com', ['Gym', 'Conference Room'], 'Hotel has 3 floors. The hotel consists of a three-story building. There are 35 rooms in total.', 35),
    new Hotel(7, 'Hotel Milan', 7, 2, 'Stylish hotel located in the fashion capital of Milan. Indulge in luxury accommodations and discover the city\'s renowned shopping districts.', 'Luxury suite', 'All Inclusive', 'Near the fashion district', '40m to the beach', 'Corso Buenos Aires 33', '+1122334455', 'milan@example.com', ['Parking', 'Swimming Pool'], 'Hotel has 4 floors. The hotel consists of a four-story building. There are 25 rooms in total.', 25),
    new Hotel(8, 'Hotel Venice', 8, 2, 'Quaint hotel nestled in the romantic city of Venice. Enjoy a magical stay surrounded by picturesque canals and historic landmarks.', 'Standard room', 'Only Breakfast', 'Located near St. Mark\'s Square', '15m to the beach', 'Calle Larga XXII Marzo 77', '+9988776655', 'venice@example.com', ['Spa', 'Bar'], 'Hotel has 5 floors. The hotel consists of a five-story building. There are 45 rooms in total.', 4),

    // Готелі для країни з id_country = 3 (France)
    new Hotel(9, 'Hotel Paris', 9, 3, 'Chic hotel situated in the heart of Paris, offering stylish accommodations and easy access to the city\'s most iconic attractions.', 'Luxury suite', 'Only Breakfast', 'Near the Louvre Museum', '10m to the beach', 'Avenue des Champs-Élysées 101', '+123456789', 'paris@example.com', ['Free Wi-Fi', 'Room Service'], 'Hotel has 7 floors. The hotel consists of a seven-story building. There are 70 rooms in total.', 70),
    new Hotel(10, 'Hotel Lyon', 10, 3, 'Contemporary hotel located in the vibrant city of Lyon. Discover the city\'s culinary delights and cultural treasures from this convenient location.', 'Standard room', 'Only Dinner', 'Close to Old Lyon', '20m to the beach', 'Rue de la République 22', '+987654321', 'lyon@example.com', ['Gym', 'Restaurant'], 'Hotel has 4 floors. The hotel consists of a four-story building. There are 40 rooms in total.', 40),
    new Hotel(11, 'Hotel Marseille', 11, 3, 'Relaxing hotel nestled along the picturesque coast of Marseille. Enjoy stunning sea views and explore the city\'s vibrant neighborhoods.', 'Standard room', 'All Inclusive', 'Conveniently located near the port', '30m to the beach', 'Quai du Port 14', '+1122334455', 'marseille@example.com', ['Bar', 'Swimming Pool'], 'Hotel has 3 floors. The hotel consists of a three-story building. There are 30 rooms in total.', 30),
    new Hotel(12, 'Hotel Nice', 12, 3, 'Tranquil hotel located in the charming city of Nice. Relax in stylish accommodations and soak up the Mediterranean sun from the hotel\'s terrace.', 'Deluxe room', 'Only Breakfast', 'Central location in Nice', '5m to the beach', 'Promenade des Anglais 66', '+9988776655', 'nice@example.com', ['Spa', 'Free Parking'], 'Hotel has 5 floors. The hotel consists of a five-story building. There are 50 rooms in total.', 50),

    // Готелі для країни з id_country = 4 (Spain)
    new Hotel(13, 'Hotel Madrid', 13, 4, 'Vibrant hotel located in the bustling city of Madrid. Experience the energy of the Spanish capital from this centrally located hotel.', 'Standard room', 'Only Breakfast', 'In the heart of Madrid', '10m to the beach', 'Gran Vía 123', '+123456789', 'madrid@example.com', ['Room Service', 'Bar'], 'Hotel has 8 floors. The hotel consists of an eight-story building. There are 80 rooms in total.', 8),
    new Hotel(14, 'Hotel Barcelona', 14, 4, 'Modern hotel situated in the vibrant city of Barcelona. Enjoy stunning views of the city skyline from the rooftop terrace.', 'Luxury suite', 'All Inclusive', 'Near the Gothic Quarter', '20m to the beach', 'Passeig de Gràcia 45', '+987654321', 'barcelona@example.com', ['Free Wi-Fi', 'Restaurant'], 'Hotel has 7 floors. The hotel consists of a seven-story building. There are 55 rooms in total.', 55),
    new Hotel(15, 'Hotel Valencia', 15, 4, 'Elegant hotel located in the historic city of Valencia. Immerse yourself in luxury and comfort during your stay in this charming Mediterranean city.', 'Standard room', 'Only Dinner', 'Central location in Valencia', '15m to the beach', 'Calle de la Paz 78', '+1122334455', 'valencia@example.com', ['Gym', 'Parking'], 'Hotel has 6 floors. The hotel consists of a six-story building. There are 45 rooms in total.', 45),
    new Hotel(16, 'Hotel Seville', 16, 4, 'Tranquil hotel nestled in the heart of Seville. Experience the magic of Andalusia from this charming hotel located near the city\'s top attractions.', 'Standard room', 'Only Breakfast', 'Close to the Cathedral', '25m to the beach', 'Avenida de la Constitución 33', '+9988776655', 'seville@example.com', ['Swimming Pool', 'Conference Room'], 'Hotel has 9 floors. The hotel consists of a nine-story building. There are 65 rooms in total.', 65),

    // Готелі для країни з id_country = 5 (UK)
    new Hotel(17, 'Hotel London', 17, 5, 'Iconic hotel located in the heart of London. Immerse yourself in British luxury and elegance during your stay in the capital city.', 'Luxury suite', 'All Inclusive', 'Near Buckingham Palace', '10m to the beach', 'Buckingham Palace Road 10', '+123456789', 'london@example.com', ['Free Wi-Fi', 'Bar'], 'Hotel has 10 floors. The hotel consists of a ten-story building. There are 90 rooms in total.', 0),
    new Hotel(18, 'Hotel Manchester', 18, 5, 'Contemporary hotel situated in the vibrant city of Manchester. Enjoy modern amenities and personalized service at this centrally located hotel.', 'Standard room', 'Only Breakfast', 'Close to Manchester Arena', '15m to the beach', 'Deansgate 55', '+987654321', 'manchester@example.com', ['Parking', 'Restaurant'], 'Hotel has 5 floors. The hotel consists of a five-story building. There are 50 rooms in total.', 50),
    new Hotel(19, 'Hotel Liverpool', 19, 5, 'Quirky hotel located in the lively city of Liverpool. Experience the city\'s rich musical heritage and cultural diversity from this unique hotel.', 'Standard room', 'Only Dinner', 'Conveniently located near Albert Dock', '20m to the beach', 'Mathew Street 20', '+1122334455', 'liverpool@example.com', ['Room Service', 'Gym'], 'Hotel has 4 floors. The hotel consists of a four-story building. There are 40 rooms in total.', 40),
    new Hotel(20, 'Hotel Birmingham', 20, 5, 'Modern hotel situated in the bustling city of Birmingham. Discover the city\'s vibrant nightlife and cultural attractions from this conveniently located hotel.', 'Deluxe room', 'All Inclusive', 'Central location in Birmingham', '30m to the beach', 'Broad Street 30', '+9988776655', 'birmingham@example.com', ['Swimming Pool', 'Free Parking'], 'Hotel has 8 floors. The hotel consists of an eight-story building. There are 70 rooms in total.', 70)
];
